### ISSUE TITLE
Fetch results in error

### ISSUE THREAD

**Issue by hhumml** [contentful/contentful.java#102]
Code
```
CDAArray pages = client.fetch(CDAEntry.class).where("contentType","Page").all();
		if(pages.items().size() > 0) {
			System.out.println("Pages found: ");
			for(CDAResource page : pages.items()) {
				System.out.println("* " + ((CDAEntry) page).getField("title"));
			}
		}
```
Result
```
Exception in thread "main" retrofit.RetrofitError: 400 Bad Request
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
	at retrofit.RxSupport$2.run(RxSupport.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at retrofit.Platform$Base$2$1.run(Platform.java:94)
	at java.lang.Thread.run(Thread.java:744)
```
Without the where clause it works. I also tried "content_type" as shown in the readme file but this also does not work.

**Comment by tomxor** [comment]
Using `contentType` instead of `content_type` will always result in a 400 response. Another case in which you'll hit 400 is when you provide an invalid content type ID. It's unlikely that the ID of your content type is `Page` (although possible, via the CMA). 

You can extract the content type ID by logging into the Contentful web app, hit the `Content Types` button on the top bar, select the desired content type, and copy the last path segment of the URL. Example:

![](https://www.contentful.com/developers/docs/tutorials/android/content-type-id-c0bd618f.png)

On a side note, when creating a `CDAClient` instance, you can always use `setLogLevel(LogLevel.FULL)` to show the request+response logs, which might help figuring out the issue, in this case you could see something similar to:

```json
{
  "sys": {
    "type": "Error",
    "id": "InvalidQuery"
  },
  "message": "The query you sent was invalid. Probably a filter or ordering specification is not applicable to the type of a field.",
  "details": {
    "errors": [
      {
        "name": "unknownContentType",
        "value": "DOESNOTEXIST"
      }
    ]
  },
  "requestId": "foo"
}
```

**Comment by tomxor** [comment]
Another unrelated comment is that `CDAArray.items()` might contain mixed types, meaning both `CDAEntry` instances and also included `CDAAsset` instances. If you're interested only in the entries, you can iterate over `CDAArray.entries().values()` instead.

**Comment by hhumml** [comment]
Thank´s for the hints!
