### ISSUE TITLE
CDA Sync Class Cast Exception

### ISSUE THREAD

**Issue by jataggart** [contentful/contentful.java#111]
I am trying to do an initial sync and it is throwing a `java.lang.ClassCastException`.

```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to java.util.List
	at com.contentful.java.cda.ResourceUtils.resolveArrayOfLinks(ResourceUtils.java:96) ~[java-sdk-6.0.0.jar:na]
	at com.contentful.java.cda.ResourceUtils.resolveLinks(ResourceUtils.java:65) ~[java-sdk-6.0.0.jar:na]
	at com.contentful.java.cda.ResourceFactory.sync(ResourceFactory.java:77) ~[java-sdk-6.0.0.jar:na]
	at com.contentful.java.cda.SyncQuery$1.call(SyncQuery.java:49) ~[java-sdk-6.0.0.jar:na]
	at com.contentful.java.cda.SyncQuery$1.call(SyncQuery.java:47) ~[java-sdk-6.0.0.jar:na]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:364) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:326) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:802) ~[rxjava-1.0.14.jar:1.0.14]
	at retrofit.RxSupport$2.run(RxSupport.java:56) ~[retrofit-1.9.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at retrofit.Platform$Base$2$1.run(Platform.java:94) ~[retrofit-1.9.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit.client.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:104) ~[rxjava-1.0.14.jar:1.0.14]
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58) ~[rxjava-1.0.14.jar:1.0.14]
```

Here is my code:

```java
CDAClient.Builder builder = CDAClient.builder().setSpace(contentfulSpace).setToken(contentfulToken);
CDAClient contentfulClient = builder.build();

// grabbed this syntax from the unit test, throws ClassCastException
SynchronizedSpace synchronizedSpace = contentfulClient.sync().observe().toBlocking().first();

// I've also tried the following, still throws ClassCastException
// SynchronizedSpace synchronizedSpace = contentfulClient.sync().fetch();
```

Not quite sure what is happening here

**Comment by mariobodemann** [comment]
Hey,

as discussed via support messaging, we are not supporting `sync` in `preview` mode. Please use a `production api key` for `syncing`.

Greetings,
Mario

**Comment by jataggart** [comment]
Thanks Mario.
