### ISSUE TITLE
Query with "select" criteria doesn't work

### ISSUE THREAD

**Issue by mrroman** [contentful/contentful.java#134]
1. You can't select only sys.id field, it throws NullPointerException

E.g.

```java
cdaClient.fetch(CDAEntry.class)
                .where("select", "sys.id")
```

you get

```
java.lang.NullPointerException
	at com.contentful.java.cda.ResourceDeserializer.extractType(ResourceDeserializer.java:33)
	at com.contentful.java.cda.ResourceDeserializer.deserialize(ResourceDeserializer.java:19)
	at com.contentful.java.cda.ResourceDeserializer.deserialize(ResourceDeserializer.java:16)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
```

2. If you add sys.type field, it throws another exception.

E.g.

```java
cdaClient.fetch(CDAEntry.class)
                .where("select", "sys.id,sys.title")
```

you get

```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at com.contentful.java.cda.CDAClient.cacheTypeWithId(CDAClient.java:269)
	at com.contentful.java.cda.ResourceUtils.ensureContentType(ResourceUtils.java:79)
	at com.contentful.java.cda.ResourceUtils.resolveLinks(ResourceUtils.java:61)
	at com.contentful.java.cda.ResourceFactory.array(ResourceFactory.java:38)
	at com.contentful.java.cda.ObserveQuery$3.call(ObserveQuery.java:75)
	at com.contentful.java.cda.ObserveQuery$3.call(ObserveQuery.java:73)
```

3. I added one of the fields, but it appears that the API works different when you select field or load whole document. It returns just a string and not an object, when you select field. So it throws this exception:

E.g.

```java
cdaClient.fetch(CDAEntry.class)
                .where("select", "sys.id,sys.type,fields.title")
```

you get

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map

	at com.contentful.java.cda.ResourceUtils.setRawFields(ResourceUtils.java:286)
	at com.contentful.java.cda.ResourceUtils.setRawFields(ResourceUtils.java:277)
	at com.contentful.java.cda.ResourceFactory.array(ResourceFactory.java:37)
	at com.contentful.java.cda.ObserveQuery$3.call(ObserveQuery.java:75)
	at com.contentful.java.cda.ObserveQuery$3.call(ObserveQuery.java:73)
```

**Comment by mariobodemann** [comment]
Hey,

Thanks for reaching out to us. As you found out, `select` queries are not yet 100% supported. 

My recommendation is trying to select the complete `sys` field, and that _should_ take care of the rest.

I'll verify one I do have a stable connection again.

**Comment by mariobodemann** [comment]
Hey,

I just rebuild a quick and was able to use `select`:

```
    client.observe(CDAEntry.class)
        .where("content_type", <YOUR CONTENT TYPE ID>)
        .where("select", "sys,fields.name")
        .all()
```

The main problem was to also use the `content_type`, otherwise you'll get an error message as a string, which cannot be transformed into an `CDAEntry` for obvious reasons. 

As soon as we tackle the select operator completely in Java, we should remeber to always include `sys` and make sure that if a _field_ is selected, to also select its _content type_.

Thank you for finding out, we'll make it easier soon™, that said, I cannot say when ... ;)

Also, I would be curious to know in which situation you would use the `select` operator for, what you'd like it to be, and how we could make it easier to be used.

**Comment by mrroman** [comment]
Thanks for the fast response :). I didn't know that I can select whole "sys" at once. It could be a good idea to write this solution in README file. 

I wanted it just to get id and few fields. I think that separate method that could take list of fields would be sufficient. E.g.

```java
client.fetch(CDAEntry.class)
    .where("content_type", <CONTENT_TYPE>)
    .select("title", "caption")
    .all()
```

I don't know if it is too specific (omitting attributes). Another thing is that it could be called without fields and that would mean that just "sys" is taken.

**Comment by mariobodemann** [comment]
Hey,

I'm closing this issue for now, since the with the new #144 and the new release 7.5.0, we have the ability to use the select query like follows:

```
    final CDAArray all =
        client
            .fetch(CDAEntry.class)
            .withContentType("<content_type_id>")
            .select(
              "fields.productName",
              "fields.websiteName")
            .all();
```

The `sys` field will always be included. So please let me know what you think...
