### ISSUE TITLE
java.lang.IllegalArgumentException when building the user agent string

### ISSUE THREAD

**Issue by fcduarte** [contentful/contentful.java#157]
Hi,

I've seen a few bug reports that when the SDK tries to build the user agent and send it to OkHttp in some situations it led to an IllegalArgumentException. 

First situation is on a LG D851 device:

````
Caused by: java.lang.IllegalArgumentException: Unexpected char 0x2122 at 60 in User-Agent value: contentful.java/7.6.2(Android Runtime 0.9) Linux/3.4.0-Xceed™-D851
        at okhttp3.Headers$Builder.checkNameAndValue(SourceFile:321)
        at okhttp3.Headers$Builder.add(SourceFile:271)
        at okhttp3.Request$Builder.addHeader(SourceFile:177)
        at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(SourceFile:38)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
        at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(SourceFile:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
        at okhttp3.RealCall.execute(SourceFile:69)
        at retrofit2.OkHttpCall.execute(SourceFile:180)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(SourceFile:40)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(SourceFile:24)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.subscribe(SourceFile:10247)
        at rx.Observable.subscribe(SourceFile:10214)
        at rx.observables.BlockingObservable.blockForSingle(SourceFile:444)
        at rx.observables.BlockingObservable.first(SourceFile:167)
        at com.contentful.java.cda.FetchQuery.all(SourceFile:43)
````

Second situation is on a few devices set with Arabic languages like fa_IR, ar_EG, ar_AE and bn_BD:

````
Caused by: java.lang.IllegalArgumentException: Unexpected char 0x6f7 at 20 in X-Contentful-User-Agent value: sdk contentful.java/۷.۶.۲; platform java/۰.۹.۰; os Android/۶.۰.۱; 
        at okhttp3.Headers$Builder.checkNameAndValue(SourceFile:321)
        at okhttp3.Headers$Builder.add(SourceFile:271)
        at okhttp3.Request$Builder.addHeader(SourceFile:177)
        at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(SourceFile:38)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
        at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(SourceFile:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
        at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(SourceFile:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
        at okhttp3.RealCall.execute(SourceFile:69)
        at retrofit2.OkHttpCall.execute(SourceFile:180)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(SourceFile:40)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(SourceFile:24)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.unsafeSubscribe(SourceFile:10151)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeMap.call(SourceFile:33)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:48)
        at rx.internal.operators.OnSubscribeLift.call(SourceFile:30)
        at rx.Observable.subscribe(SourceFile:10247)
        at rx.Observable.subscribe(SourceFile:10214)
        at rx.observables.BlockingObservable.blockForSingle(SourceFile:444)
        at rx.observables.BlockingObservable.first(SourceFile:167)
        at com.contentful.java.cda.FetchQuery.all(SourceFile:43)
````

Suggestion is to not rely on system properties when running on an Android environment since you can't control what values will come from there.

Thanks!

**Comment by mariobodemann** [comment]
Hello @fcduarte,

thank you for this detailed report. Sadly we have to rely on some of the `System`-properties to be able to track how this SDK is used, on which platform, language, etc.

Instead of dropping the much needed support we'll update the header generation to have a more generous fallback mechanism.

Thanks again for the report, I'll be reporting back as soon as we have a solution.

**Comment by mariobodemann** [comment]
Hey,

I am happy to announce, that your issue should be closed with the new release: https://github.com/contentful/contentful.java/releases/tag/java-sdk-8.0.1

Please let me know if we can do anything more for you.

**Comment by n8ebel** [comment]
I seem to be encountering the same issue on this version `com.contentful.java:java-sdk:9.0.1`

Occurring when testing on a stock Pixel XL 2 Android emulator with api 27 & 25 using the following locales `ar` & `ar_EG`

## Error Msg
`Unexpected char 0x669 at 20 in X-Contentful-User-Agent value: sdk contentful.java/٩.٠.١; platform java/٠.٩.٠; os Android/٨.١.٠; `

**Comment by mariobodemann** [comment]
Hey,

I am sorry to hear that. Let me investigate if there is another way of addressing this problem ...

**Comment by Bartoshr** [comment]
Hi. 
I found similar problem while using version `10.5.17`

Model: Poco X3 Pro

          Caused by java.lang.IllegalArgumentException: Unexpected char 0x2122 at 66 in User-Agent value: contentful.java/10.5.17(Android Runtime 0.9) Linux/4.14.355-Helios™/afb012a0
       at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
       at okhttp3.Headers$Companion.access$checkValue(Headers.kt)
       at okhttp3.Headers$Builder.add(Headers.kt:261)
       at okhttp3.Request$Builder.addHeader(Request.kt:210)
       at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:39)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:38)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
