### ISSUE TITLE
Setting a timeout for CDAClient fetch is not documentend

### ISSUE THREAD

**Issue by ristomatti** [contentful/contentful.java#173]
It would be important to be able to set a timeout for the queries as can be done with contentful.js. I tried to find this in the documentation and also skimmed through some of the source code but did not even find what the default timeout is. 

Sorry if this is already there but in that case please point me to the documentation how to set the timeout.

**Comment by mariobodemann** [comment]
Hello,

You need to create a CDAClient.Builder as normally, and just before you call `.build()` on it you need to call [defaultCallFactoryBuilder()](https://github.com/contentful/contentful.java/blob/master/src/main/java/com/contentful/java/cda/CDAClient.java#L706).

This will give you a `OkHttp.Builder`, which you then can use to set the timeouts of the ok http library: 

```
.connectTimeout(10,TimeUnit.SECONDS)
.writeTimeout(10,TimeUnit.SECONDS)
.readTimeout(30,TimeUnit.SECONDS)
```

Now you need to provide this okhttp call factory back to the CDAClient.Builder by using the [setCallFactory]
(https://github.com/contentful/contentful.java/blob/master/src/main/java/com/contentful/java/cda/CDAClient.java#L605)-method. And as a last step you can call CDAClient.Builder.build() as usual.

I hope that could get you a hint on how to continue,

Greetings,
Mario

**Comment by ristomatti** [comment]
@mariobodemann Thanks! This is enough for me know but I still believe this should be documented somewhere. Even better would be if `CDAClient` would expose these settings on it's own API.

I've modified the issue name to reflect the lack of documentation.

**Comment by ristomatti** [comment]
@mariobodemann I tried setting the timeout as described but after that the client request failed as below:
```
com.contentful.java.cda.CDAHttpException: null
	at com.contentful.java.cda.interceptor.ErrorInterceptor.intercept(ErrorInterceptor.java:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.contentful.java.cda.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.Observable.subscribe(Observable.java:10838)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:12978)
	at io.reactivex.Flowable.blockingFirst(Flowable.java:5221)
	at com.contentful.java.cda.FetchQuery.all(FetchQuery.java:51)
```

Code used:
```java
CDAClient.Builder clientBuilder = CDAClient.builder();

OkHttpClient httpClient = clientBuilder
        .defaultCallFactoryBuilder()
        .connectTimeout(5, TimeUnit.SECONDS).build();

CDAClient cdaClient = clientBuilder
    .setCallFactory(httpClient)
    .setSpace(contentfulSpace)
    .setEnvironment(contentfulEnvironment)
    .setToken(contentfulApiKey)
    .build();
```

Any ideas?

**Comment by mariobodemann** [comment]
Hey,

you should call the `setSpace`, and `setToken` before calling the `defaultCallFactoryBuilder`: Otherwise the according headers will not be set on the call factory.

**Comment by ristomatti** [comment]
@mariobodemann I believe I tried also having it just before `build();` but I'll try again and report back.

**Comment by ristomatti** [comment]
Makes no difference, still got the same error with:
```java
            CDAClient.Builder clientBuilder = CDAClient.builder();

            OkHttpClient httpClient = clientBuilder
                    .defaultCallFactoryBuilder()
                    .connectTimeout(5, TimeUnit.SECONDS).build();

            CDAClient cdaClient = clientBuilder
                    .setSpace(contentfulSpace)
                    .setEnvironment(contentfulEnvironment)
                    .setToken(contentfulApiKey)
                    .setCallFactory(httpClient)
                    .build();
```

If I comment out `.setCallFactory(httpClient)` everything works as expected.

**Comment by ristomatti** [comment]
Nevermind! I misinterpreted your comment on the first read. This works:
```java
CDAClient.Builder clientBuilder = CDAClient.builder()
        .setSpace(salesOrganization.contentfulSpace)
        .setEnvironment(salesOrganization.contentfulEnvironment)
        .setToken(salesOrganization.contentfulApiKey);

OkHttpClient httpClient = clientBuilder.defaultCallFactoryBuilder()
        .connectTimeout(5, TimeUnit.SECONDS)
        .build();

CDAClient cdaClient = clientBuilder.setCallFactory(httpClient).build();
```

In my opinion the solution is not exactly obvious and it would be a lot better to expose the methods directly on the CDAClient API.

**Comment by mariobodemann** [comment]
Thank you for your feedback,

we will be thinking about how to improve the usabillity, but for now I'm happy you got it working, and am closing this ticket.

Please feel free to reach out to us again anytime ...
