### ISSUE TITLE
v10.2.0 fails inside CDAClient.fetch().all()

### ISSUE THREAD

**Issue by vmalikov** [contentful/contentful.java#181]
Hi guys!
I'm trying to fetch data from Contentful via com.contentful.java:java-sdk:10.2.0 and it fails because of BootstrapMethodError inside CDAClient.cacheLocales method. But if I switch the version to 10.1.0 - all works like a charm. 

I've tried the sample from https://github.com/contentful/rich-text-renderer.java. And sample builds and shows mock data, but when I've added API request - the app fails. 
Here is the code from sample + fetching CDAArray with all data: http://prntscr.com/m0locu

Can somebody suggest how to fix it? Or maybe you can make a hotfix? 

Crash log:
```
Process: com.contentful.rich.android.sample, PID: 16815
    java.lang.BootstrapMethodError: Exception from call site #2 bootstrap method
        at com.contentful.java.cda.CDAClient.cacheLocales(CDAClient.java:378)
        at com.contentful.java.cda.CDAClient.cacheAll(CDAClient.java:370)
        at com.contentful.java.cda.ObserveQuery.all(ObserveQuery.java:83)
        at com.contentful.java.cda.FetchQuery.all(FetchQuery.java:51)
        at com.contentful.rich.android.sample.MainActivity.fetch(MainActivity.kt:61)
        at com.contentful.rich.android.sample.MainActivity.onCreate(MainActivity.kt:49)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.contentful.java.cda.CDAClient.cacheLocales(CDAClient.java:378) 
        at com.contentful.java.cda.CDAClient.cacheAll(CDAClient.java:370) 
        at com.contentful.java.cda.ObserveQuery.all(ObserveQuery.java:83) 
        at com.contentful.java.cda.FetchQuery.all(FetchQuery.java:51) 
        at com.contentful.rich.android.sample.MainActivity.fetch(MainActivity.kt:61) 
        at com.contentful.rich.android.sample.MainActivity.onCreate(MainActivity.kt:49) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
```

**Comment by mariobodemann** [comment]
Hello,

thanks for reporting this behaviour. My initial thought is the min sdk version is set wrong, but I will investigate further and come up with a solution for you...

**Comment by vmalikov** [comment]
Hey @mariobodemann thank you for your response!
After I've added compileOptions - app doesn't crashes!
