### ISSUE TITLE
Build Conflicts with GSON

### ISSUE THREAD

**Issue by CodyEddings** [contentful/contentful.java#211]
Hi,

I'm having a gradle build conflict with Contentful library and other libraries in my Android project and I can't resolve them. Gson seems to be the culprit. I have full build logs to provide with various configurations.

I've tried 2 main approaches:
1)
```
implementation (deps.contentful.contentful) {
exclude group: 'com.google.code.gson', module: 'gson'
}
```
This causes a runtime error when contentful tries to fetch data:
```
2020-04-08 16:08:08.515 23862-24067/com.nu.rms.kiosklauncher E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.nu.rms.kiosklauncher, PID: 23862
java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /data/app/com.nu.rms.kiosklauncher-2/base.apk)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
at io.reactivex.Observable.subscribe(Observable.java:12246)
at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
at io.reactivex.Flowable.subscribe(Flowable.java:14805)
at io.reactivex.Flowable.blockingFirst(Flowable.java:5607)
at com.contentful.java.cda.FetchQuery.one(FetchQuery.java:26)
at com.nu.rms.kiosklauncher.ui.viewmodel.AppsViewModel$loadMinimumAppVersion$1.invokeSuspend(AppsViewModel.kt:36)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

2) `implementation deps.contentful.contentful`
This causes a build error because of a conflict with another api project our app declares as a dependency that uses gson:

`Type com.google.gson.FieldNamingPolicy$3 is defined multiple times: /Users/ceddings/StudioProjects/r15-android-rms-kiosk-launcher/kiosk/build/intermediates/mixed_scope_dex_archive/debug/out/2fcf9ca3ebe4bba6e5de15039706dbd823b837def40fd130c6d32dbf72d7d3fe_5.jar:classes.dex, /Users/ceddings/StudioProjects/r15-android-rms-kiosk-launcher/kiosk/build/intermediates/mixed_scope_dex_archive/debug/out/ea224b570661b7f603dabaea5da8866923e8add942f1c7af0ec48f1acd739e6e_5.jar:classes.dex`

What's the correct solution here? For reference, I also made a stackoverflow post but I haven't gained any insight from it yet. https://stackoverflow.com/questions/61022373/type-com-google-gson-exclusionstrategy-is-defined-multiple-times

**Comment by rafalniski** [comment]
Hey @CodyEddings ,

can I see your dependency tree? Could you paste here output of the `./gradlew app:dependencies
`

**Comment by rafalniski** [comment]
Closing this because of no activity, please reopen if problem still happens.
