### ISSUE TITLE
Exception when using sync api of cdaClient

### ISSUE THREAD

**Issue by saurabh782** [contentful/contentful.java#312]
Hi Team,
I am getting the following error while using the sync api through the contentful java sdk.I am using the cda client.
This is the following error that I am getting:
**Cannot invoke "com.contentful.java.cda.rich.CDARichDocument.getContent()" because "document" is null**

My only line of code is :
cdaClient.sync().fetch()

Pls help out here.

**Comment by ckolek-figs** [comment]
Our team is running into the same exception:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.contentful.java.cda.rich.CDARichDocument.getContent()" because "document" is null
	at com.contentful.java.cda.rich.RichTextFactory.resolveRichLink(RichTextFactory.java:171)
	at com.contentful.java.cda.rich.RichTextFactory.resolveRichTextField(RichTextFactory.java:80)
	at com.contentful.java.cda.ResourceFactory.array(ResourceFactory.java:33)
	at com.contentful.java.cda.ObserveQuery$1.apply(ObserveQuery.java:106)
	at com.contentful.java.cda.ObserveQuery$1.apply(ObserveQuery.java:103)
```

This seems to occur when resolving a field with the ID `rtfFeatures`, which appears to be null across all locales:

![Image](https://github.com/user-attachments/assets/315a25db-0533-4ca8-a552-716ea72414b6)
